setwd("C:/Users/marora/Desktop/regression")
data2 = read.csv("nyc.csv", header = T)
plot(data2$Food,data2$Price)
my.linear<-lm(data2$Price~data2$Food)
summary(my.linear)
abline(my.linear)
plot(data2$Decor,data2$Price)
my.linear1<-lm(data2$Price~data2$Decor)
summary(my.linear1)
abline(my.linear1)
boxplot(data2$Decor)
boxplot(data2$East)
